### ISSUE TITLE
Rain pr hour

### ISSUE THREAD

**Issue by Tntdruid** [hugokernel/esphome-weather-station#8]
Any way to add that?

```
  - platform: integration
    name: "rainfall per hour"
    id: rain_per_h
    time_unit: h
    unit_of_measurement: 'mm'
    icon: 'mdi:weather-rainy'
    sensor: rain_gauge
```

Does not work.

**Comment by hugokernel** [comment]
Hi,

The simplest way to do that is to use the copy integration and use the result from the `rain_per_min` sensor like that:

```yaml
binary_sensor:
  - platform: copy
    source_id: rain_per_min
    name: "${friendly_name} rainfall per hour"
    filters:
      - multiply: 60
```
